### PR TITLE
Forward master

### PR DESCRIPTION
**Pull request by rhaschke**
This set of commits comprises several minor improvements to the demos, fixing recently raised issues (#113, #114).
Most importantly, the last commit should provide compatibility to the MoveIt master branch.
If you are fine with these commits, @v4hn, please fast-forward master.

### CODE REVIEW

**Comment by v4hn** [comment]
Would it make sense to you to address `master` deprecations with the same `ifdef` style?
Afaik, this currently means relates to the two other "migration" commits [in the `moveit-master' branch](https://github.com/ros-planning/moveit_task_constructor/commits/moveit-master)

**Comment by rhaschke** [comment]
I only applied the strictly required migration commit so far. Introducing ifdefs for all of them should be feasible, given the rather small amount of changes. To be honest, I didn't look into them in detail until now.

**Comment by v4hn** [comment]
> To be honest, I didn't look into them in detail until now.

No need to, thanks for setting up the ifdef logic.
I mostly wanted to know whether you're ok with ifdefs to get rid of deprecation warnings.

**Comment by rhaschke** [comment]
I'm fine with this, but I don't have time and the (urgent) need for it right now :wink:

**Pull request merged**
