### PR TITLE
Printing success log only if execution completes

### PR DESCRIPTION
**Pull request by iamrajee**
Previous code will print/log "Execution complete" even if the execution was disabled.

### CODE REVIEW

**Comment by iamrajee** [comment]
> Previous code will print/log "Execution complete" even if the execution was disabled.

Can someone explain why this commit failed to built [here](https://travis-ci.org/ros-planning/moveit_task_constructor/jobs/637957394?utm_medium=notification&utm_source=github_status)?

**Comment by rhaschke** [comment]
Please fix the clang-format issue as detailed in the Travis log. Note that you can unfold the lines to access more detailed information.

**Comment by iamrajee** [comment]
> Please fix the clang-format issue as detailed in the Travis log. Note that you can unfold the lines to access more detailed information.

Thanks for your guidance. I have fixed it.

**Comment by rhaschke** [comment]
@mamoll, thanks for having merged this. Please, consider our merge strategy in future: both #124 and #125 should have been squash-merged.

**Pull request merged**
