### PR TITLE
set useful build-options from MoveIt also in MTC

### LINKED ISSUE #385: Building using catkin_make failed in ros-melodic
Description:
1. Was trying to catkin_make to build package on ros-melodic on nvidia jetpack (Ubuntu 16.04)
2. Errors:

- error: use of ‘auto’ in lambda parameter declaration only available with -std=c++14 or -std=gnu++14

Error Logs
```
/home/hivebotics/Developer/abluo_ros_ws/src/moveit_task_constructor/visualization/motion_planning_tasks/utils/flat_merge_proxy_model.cpp: In member function ‘std::vector<moveit_rviz_plugin::utils::FlatMergeProxyModelPrivate::ModelData>::iterator moveit_rviz_plugin::utils::FlatMergeProxyModelPrivate::find(const QObject*)’:
/home/hivebotics/Developer/abluo_ros_ws/src/moveit_task_constructor/visualization/motion_planning_tasks/utils/flat_merge_proxy_model.cpp:114:65: error: use of ‘auto’ in lambda parameter declaration only available with -std=c++14 or -std=gnu++14
   return std::find_if(data_.begin(), data_.end(), [model](const auto& data) { return data.model_ == model; });
                                                                 ^~~~
/home/hivebotics/Developer/abluo_ros_ws/src/moveit_task_constructor/visualization/motion_planning_tasks/utils/flat_merge_proxy_model.cpp: In lambda function:
/home/hivebotics/Developer/abluo_ros_ws/src/moveit_task_constructor/visualization/motion_planning_tasks/utils/flat_merge_proxy_model.cpp:114:91: error: request for member ‘model_’ in ‘data’, which is of non-class type ‘const int’
   return std::find_if(data_.begin(), data_.end(), [model](const auto& data) { return data.model_ == model; });
                                                                                           ^~~~~~
/home/hivebotics/Developer/abluo_ros_ws/src/moveit_task_constructor/visualization/motion_planning_tasks/utils/flat_merge_proxy_model.cpp: In member function ‘int moveit_rviz_plugin::utils::FlatMergeProxyModelPrivate::accumulatedRowCount(std::vector<moveit_rviz_plugin::utils::FlatMergeProxyModelPrivate::ModelData>::const_iterator, std::vector<moveit_rviz_plugin::utils::FlatMergeProxyModelPrivate::ModelData>::const_iterator) const’:
/home/hivebotics/Developer/abluo_ros_ws/src/moveit_task_constructor/visualization/motion_planning_tasks/utils/flat_merge_proxy_model.cpp:119:59: error: use of ‘auto’ in lambda parameter declaration only available with -std=c++14 or -std=gnu++14
   return std::accumulate(start, end, 0, [](int acc, const auto& d) { return acc + d.model_->rowCount(); });
                                                           ^~~~
/home/hivebotics/Developer/abluo_ros_ws/src/moveit_task_constructor/visualization/motion_planning_tasks/utils/flat_merge_proxy_model.cpp: In lambda function:
/home/hivebotics/Developer/abluo_ros_ws/src/moveit_task_constructor/visualization/motion_planning_tasks/utils/flat_merge_proxy_model.cpp:119:85: error: request for member ‘model_’ in ‘d’, which is of non-class type ‘const int’
   return std::accumulate(start, end, 0, [](int acc, const auto& d) { return acc + d.model_->rowCount(); });
                                                                                     ^~~~~~
In file included from /usr/include/c++/7/numeric:62:0,
                 from /usr/include/aarch64-linux-gnu/qt5/QtCore/qhashfunctions.h:47,
                 from /usr/include/aarch64-linux-gnu/qt5/QtCore/qlist.h:47,
                 from /usr/include/aarch64-linux-gnu/qt5/QtCore/qvariant.h:45,
                 from /usr/include/aarch64-linux-gnu/qt5/QtCore/qabstractitemmodel.h:43,
                 from /usr/include/aarch64-linux-gnu/qt5/QtCore/QAbstractItemModel:1,
                 from /home/hivebotics/Developer/abluo_ros_ws/src/moveit_task_constructor/visualization/motion_planning_tasks/utils/flat_merge_proxy_model.h:39,
                 from /home/hivebotics/Developer/abluo_ros_ws/src/moveit_task_constructor/visualization/motion_planning_tasks/utils/flat_merge_proxy_model.cpp:37:
/usr/include/c++/7/bits/stl_numeric.h: In instantiation of ‘_Tp std::accumulate(_InputIterator, _InputIterator, _Tp, _BinaryOperation) [with _InputIterator = __gnu_cxx::__normal_iterator<const moveit_rviz_plugin::utils::FlatMergeProxyModelPrivate::ModelData*, std::vector<moveit_rviz_plugin::utils::FlatMergeProxyModelPrivate::ModelData> >; _Tp = int; _BinaryOperation = moveit_rviz_plugin::utils::FlatMergeProxyModelPrivate::accumulatedRowCount(std::vector<moveit_rviz_plugin::utils::FlatMergeProxyModelPrivate::ModelData>::const_iterator, std::vector<moveit_rviz_plugin::utils::FlatMergeProxyModelPrivate::ModelData>::const_iterator) const::<lambda(int, const int&)>]’:
/home/hivebotics/Developer/abluo_ros_ws/src/moveit_task_constructor/visualization/motion_planning_tasks/utils/flat_merge_proxy_model.cpp:119:106:   required from here
/usr/include/c++/7/bits/stl_numeric.h:154:22: error: no match for call to ‘(moveit_rviz_plugin::utils::FlatMergeProxyModelPrivate::accumulatedRowCount(std::vector<moveit_rviz_plugin::utils::FlatMergeProxyModelPrivate::ModelData>::const_iterator, std::vector<moveit_rviz_plugin::utils::FlatMergeProxyModelPrivate::ModelData>::const_iterator) const::<lambda(int, const int&)>) (int&, const moveit_rviz_plugin::utils::FlatMergeProxyModelPrivate::ModelData&)’
  __init = __binary_op(__init, *__first);
           ~~~~~~~~~~~^~~~~~~~~~~~~~~~~~
/usr/include/c++/7/bits/stl_numeric.h:154:22: note: candidate: void (*)(int, const int&) <conversion>
/usr/include/c++/7/bits/stl_numeric.h:154:22: note:   candidate expects 3 arguments, 3 provided
/home/hivebotics/Developer/abluo_ros_ws/src/moveit_task_constructor/visualization/motion_planning_tasks/utils/flat_merge_proxy_model.cpp:119:66: note: candidate: moveit_rviz_plugin::utils::FlatMergeProxyModelPrivate::accumulatedRowCount(std::vector<moveit_rviz_plugin::utils::FlatMergeProxyModelPrivate::ModelData>::const_iterator, std::vector<moveit_rviz_plugin::utils::FlatMergeProxyModelPrivate::ModelData>::const_iterator) const::<lambda(int, const int&)>
   return std::accumulate(start, end, 0, [](int acc, const auto& d) { return acc + d.model_->rowCount(); });
                                                                  ^
/home/hivebotics/Developer/abluo_ros_ws/src/moveit_task_constructor/visualization/motion_planning_tasks/utils/flat_merge_proxy_model.cpp:119:66: note:   no known conversion for argument 2 from ‘const moveit_rviz_plugin::utils::FlatMergeProxyModelPrivate::ModelData’ to ‘const int&’
In file included from /usr/include/c++/7/bits/stl_algobase.h:71:0,
                 from /usr/include/c++/7/algorithm:61,
                 from /usr/include/aarch64-linux-gnu/qt5/QtCore/qglobal.h:109,
                 from /usr/include/aarch64-linux-gnu/qt5/QtCore/qatomic.h:41,
                 from /usr/include/aarch64-linux-gnu/qt5/QtCore/qvariant.h:43,
                 from /usr/include/aarch64-linux-gnu/qt5/QtCore/qabstractitemmodel.h:43,
                 from /usr/include/aarch64-linux-gnu/qt5/QtCore/QAbstractItemModel:1,
                 from /home/hivebotics/Developer/abluo_ros_ws/src/moveit_task_constructor/visualization/motion_planning_tasks/utils/flat_merge_proxy_model.h:39,
                 from /home/hivebotics/Developer/abluo_ros_ws/src/moveit_task_constructor/visualization/motion_planning_tasks/utils/flat_merge_proxy_model.cpp:37:
/usr/include/c++/7/bits/predefined_ops.h: In instantiation of ‘bool __gnu_cxx::__ops::_Iter_pred<_Predicate>::operator()(_Iterator) [with _Iterator = __gnu_cxx::__normal_iterator<moveit_rviz_plugin::utils::FlatMergeProxyModelPrivate::ModelData*, std::vector<moveit_rviz_plugin::utils::FlatMergeProxyModelPrivate::ModelData> >; _Predicate = moveit_rviz_plugin::utils::FlatMergeProxyModelPrivate::find(const QObject*)::<lambda(const int&)>]’:
/usr/include/c++/7/bits/stl_algo.h:120:14:   required from ‘_RandomAccessIterator std::__find_if(_RandomAccessIterator, _RandomAccessIterator, _Predicate, std::random_access_iterator_tag) [with _RandomAccessIterator = __gnu_cxx::__normal_iterator<moveit_rviz_plugin::utils::FlatMergeProxyModelPrivate::ModelData*, std::vector<moveit_rviz_plugin::utils::FlatMergeProxyModelPrivate::ModelData> >; _Predicate = __gnu_cxx::__ops::_Iter_pred<moveit_rviz_plugin::utils::FlatMergeProxyModelPrivate::find(const QObject*)::<lambda(const int&)> >]’
/usr/include/c++/7/bits/stl_algo.h:161:23:   required from ‘_Iterator std::__find_if(_Iterator, _Iterator, _Predicate) [with _Iterator = __gnu_cxx::__normal_iterator<moveit_rviz_plugin::utils::FlatMergeProxyModelPrivate::ModelData*, std::vector<moveit_rviz_plugin::utils::FlatMergeProxyModelPrivate::ModelData> >; _Predicate = __gnu_cxx::__ops::_Iter_pred<moveit_rviz_plugin::utils::FlatMergeProxyModelPrivate::find(const QObject*)::<lambda(const int&)> >]’
/usr/include/c++/7/bits/stl_algo.h:3932:28:   required from ‘_IIter std::find_if(_IIter, _IIter, _Predicate) [with _IIter = __gnu_cxx::__normal_iterator<moveit_rviz_plugin::utils::FlatMergeProxyModelPrivate::ModelData*, std::vector<moveit_rviz_plugin::utils::FlatMergeProxyModelPrivate::ModelData> >; _Predicate = moveit_rviz_plugin::utils::FlatMergeProxyModelPrivate::find(const QObject*)::<lambda(const int&)>]’
/home/hivebotics/Developer/abluo_ros_ws/src/moveit_task_constructor/visualization/motion_planning_tasks/utils/flat_merge_proxy_model.cpp:114:109:   required from here
/usr/include/c++/7/bits/predefined_ops.h:283:11: error: no match for call to ‘(moveit_rviz_plugin::utils::FlatMergeProxyModelPrivate::find(const QObject*)::<lambda(const int&)>) (moveit_rviz_plugin::utils::FlatMergeProxyModelPrivate::ModelData&)’
  { return bool(_M_pred(*__it)); }
           ^~~~~~~~~~~~~~~~~~~~
/home/hivebotics/Developer/abluo_ros_ws/src/moveit_task_constructor/visualization/motion_planning_tasks/utils/flat_merge_proxy_model.cpp:114:75: note: candidate: moveit_rviz_plugin::utils::FlatMergeProxyModelPrivate::find(const QObject*)::<lambda(const int&)>
   return std::find_if(data_.begin(), data_.end(), [model](const auto& data) { return data.model_ == model; });
                                                                           ^
/home/hivebotics/Developer/abluo_ros_ws/src/moveit_task_constructor/visualization/motion_planning_tasks/utils/flat_merge_proxy_model.cpp:114:75: note:   no known conversion for argument 1 from ‘moveit_rviz_plugin::utils::FlatMergeProxyModelPrivate::ModelData’ to ‘const int&’
moveit_task_constructor/visualization/motion_planning_tasks/utils/CMakeFiles/motion_planning_tasks_utils.dir/build.make:62: recipe for target 'moveit_task_constructor/visualization/motion_planning_tasks/utils/CMakeFiles/motion_planning_tasks_utils.dir/flat_merge_proxy_model.cpp.o' failed
make[2]: *** [moveit_task_constructor/visualization/motion_planning_tasks/utils/CMakeFiles/motion_planning_tasks_utils.dir/flat_merge_proxy_model.cpp.o] Error 1
CMakeFiles/Makefile2:11071: recipe for target 'moveit_task_constructor/visualization/motion_planning_tasks/utils/CMakeFiles/motion_planning_tasks_utils.dir/all' failed
```

### PR DESCRIPTION
**Pull request by v4hn**
This includes the workaround to specify c++14 explicitly for Ubuntu 18.04 (checking the gcc version is not a good way to do that that, but it works and getting it more accurate is a lot of work...)

This should implicitly address #385 and Robert's problem in https://github.com/ros-planning/moveit_task_constructor/pull/380#issuecomment-1286096646 . Sorry for bypassing CI for this, as always a bad idea.

The actual problem is that Ubuntu 18.04 comes with a cmake-config/qt5 mkspecs configuration that forces c++11 by default although it's compatible with 14, which breaks the fact that c++14 is the default in compilers in 18.04 anyway...

Why do we want melodic/Ubuntu 18.04 support in the master branches again?

Fixes #385 .

### CODE REVIEW

**Review by jspricke — APPROVED** [review]

**Comment by rhaschke** [comment]
Unfortunately, this approach doesn't work with MoveIt `melodic-devel` branch: MoveIt doesn't provide the cmake function there.

> Why do we want Melodic/Ubuntu 18.04 support in the master branches again?

I didn't know that we dropped Melodic support for MTC. I'm fine to drop support for MoveIt's melodic-devel branch though. 
However, we should maintain compatibility with Melodic/Ubuntu 18.04, building MoveIt from master branch.

**Comment by rhaschke** [comment]
I am working on fixing the remaining compiler issues as well. Please wait a minute...

**Comment by v4hn** [comment]
> I am working on fixing the remaining compiler issues as well. Please wait a minute...

Too late? :) Might be fixed now... Or not.. Looks like setting the eigen include in addition as system does not fix it yet.
Sorry, I got around to look into this after preparing for IROS today. I guess you are not in Kyoto? I met Luca already. :)

>     Why do we want Melodic/Ubuntu 18.04 support in the master branches again?
> 
> I didn't know that we dropped Melodic support for MTC. I'm fine to drop support for MoveIt's melodic-devel branch though.
> However, we should maintain compatibility with Melodic/Ubuntu 18.04, building MoveIt from master branch.

Sorry, that was meant to read as "Why again do we [still] want 18.04 support". I like your proposal to drop the melodic-devel support. I'd like to drop 18.04 altogether, but building from MoveIt master on 18.04 is fine by me.

**Comment by rhaschke** [comment]
No, I'm not in Kyoto. I pushed all my fixes, which [make it work w/o issues](https://github.com/ubi-agni/moveit_task_constructor/actions/runs/3307534996).
But, I'm not sure yet regarding the [test failure](https://github.com/ros-planning/moveit_task_constructor/actions/runs/3307518605/jobs/5459212152). I didn't change anything to handle it, but it disappeared automatically?

Enjoy IROS and Kyoto!

**Comment by v4hn** [comment]
Can you enlighten me to why [setting `-Wall` et al in `TARGET_CMAKE_ARGS`](https://github.com/ros-planning/moveit_task_constructor/pull/386/commits/1303d5f93dafd4bc3e2545b560a14ab2e6b2bfce) fixes [the system include error triggered in the target workspace](https://github.com/ros-planning/moveit_task_constructor/actions/runs/3307518605/jobs/5459212202)? Doesn't that accidentally deactivate *all* `-W` flags because they will be consumed by cmake instead of the compiler?

**Comment by v4hn** [comment]
> I'm not sure yet regarding the [test failure](https://github.com/ros-planning/moveit_task_constructor/actions/runs/3307518605/jobs/5459212152). I didn't change anything to handle it, but it disappeared automatically?

Yes, it seems we have a spurious failure in the test...

**Comment by rhaschke** [comment]
I finally fixed the unit test newly failing with clang. I cleaned up the history and pushed a new PR: #387. Closing here.

**Pull request closed without merging**
