### PR TITLE
remove underscore from public members in MotionPlanResponse

### PR DESCRIPTION
**Pull request by peterdavidfagan**
Required to align with changes introduced by [8bfe782d6254997d185644fa3eb358d2b79d69b2](https://github.com/ros-planning/moveit2/commit/8bfe782d6254997d185644fa3eb358d2b79d69b2).

### CODE REVIEW

**Review by JafarAbdi — APPROVED** [review]

**Comment by peterdavidfagan** [comment]
@JafarAbdi do you know if anyone is working on the patch for the tutorials repo?

**Comment by sjahr** [comment]
:thinking: @JafarAbdi This API change is merged into MoveIt2 rolling but not into humble or foxy. If we merge this PR, these two will be broken. What do you think is the best way to deal with this? Backport the change in MoveIt2 to Humble and wait for a release or opening a rolling branch here?

**Comment by peterdavidfagan** [comment]
Apologies I was working on something else for a short while. The above commit should resolve the CI issue for rolling (the workspace I was running had rosdep of ros-rolling-moveit-ros-planning which was messing my local testing). Hopefully CI should pass now if/when rerun.

**Comment by peterdavidfagan** [comment]
I don't have time today to investigate the test case failure spotted by CI but I will add it to my list of things to do this week.

**Comment by JafarAbdi** [comment]
> I don't have time today to investigate the test case failure spotted by CI but I will add it to my list of things to do this week.

I'll take a look at that, I think it's flaky due to a problem in rcl not mtc

**Review by henningkayser — APPROVED** [review]

**Comment by henningkayser** [comment]
I created a Humble branch for this API breakage, let's get this merged

**Pull request merged**
